### ISSUE TITLE
Feature Request: Set default contact method

### ISSUE THREAD

**Issue by davidarmstronglewis** [terraform-providers/terraform-provider-pagerduty#108]
### Terraform Version
```
Terraform v0.11.11
+ provider.pagerduty v1.2.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- pagerduty_user
- pagerduty_user_contact_method

### Terraform Configuration Files
N/A

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Some support for setting preferred contact method for a User should be supported. It looks like the User has a `default` contact method, which I'd like to not be email and instead a phone call since that's more likely to be immediately noticeable.

### Actual Behavior
It's just not supported

### Steps to Reproduce
N/A

### Important Factoids
My ideal scenario is that I could define a company-wide PagerDuty roster with everyone's preferred contact info in it so that in the case of our infrastructure's Cloudwatch Alarms going off, we'd be notified in the most direct way possible. For most of us, that's via a direct phone call. Currently, I'm able to create those Teams and Users for a project, but if I want to define the `default` contact method, I need to go through the PagerDuty website on a user-by-user basis.

### References
N/A

**Comment by heimweh** [comment]
Hi @davidarmstronglewis,

I think this is now possible using the `pagerduty_user_contact_method` resource.

Closing this for now but feel free to re-open if you want 🙂
