### ISSUE TITLE
PageDuty how to create service Extension via terraform 

### ISSUE THREAD

**Issue by nserebry** [terraform-providers/terraform-provider-pagerduty#11]
Hi ,

Can't find the way to create `Extensions` via terraform
I'm trying to setup slack extension instead using webhook .

### Terraform Version
Terraform v0.9.8

### Affected Resource(s)

<img width="900" alt="cursor_and_tools_-_datadog_-_pagerduty" src="https://user-images.githubusercontent.com/5048814/27602495-dabd9980-5b27-11e7-8b59-efc2f0e1166f.png">

Was checking docs here: https://www.terraform.io/docs/providers/pagerduty/r/service_integration.html 

Thank you for the help,
N

**Comment by heimweh** [comment]
Hi @nserebry, unfortunately it's currently not possible to manage `Extensions` via the PagerDuty API. If support is added for this in the future, I would definitely want to see that this also can be managed via Terraform as well.

Sorry that I couldn't be of more help here.

Best,

Alexander

**Comment by stack72** [comment]
Hi @nserebry / @heimweh 

As this isn't available in the API, I am going to close this out. This is something that should be filed with PagerDuty :)

Paul

**Comment by pdecat** [comment]
> As this isn't available in the API, I am going to close this out. This is something that should be filed with PagerDuty :)

Looks like this is no longer true, all standard CRUD operations on Extensions are now exposed in the API: 

> A PagerDuty Extension represents an instance of an Extension Schema on a object that an Extension can be attached to, such as a Service.
> An example of an Extension would be a Generic Webhook endpoint, a specific Slack or Hipchat channel, or a Status Page Webhook.

https://v2.developer.pagerduty.com/page/api-reference#!/Extensions/post_extensions

**Comment by pdecat** [comment]
@stack72 oh, did you mean _not available in the go-pagerduty client_?

https://github.com/heimweh/go-pagerduty/tree/master/pagerduty

**Comment by pdecat** [comment]
Work started in https://github.com/heimweh/go-pagerduty/pull/19

**Comment by shellshock1953** [comment]
FYI, heimweh/go-pagerduty#19 is merged 2 weeks ago and https://github.com/heimweh/go-pagerduty/issues/18 is closed!
