### ISSUE TITLE
Migrate Codebase from govendor to Go Modules

### ISSUE THREAD

**Issue by chenrui333** [terraform-providers/terraform-provider-pagerduty#111]
### Description
Go 1.11 has introduced [Go modules](https://github.com/golang/go/wiki/Modules), which looks like the official solution for dependency management going forward.

### References
terraform-providers/terraform-provider-aws#5773
https://github.com/golang/go/wiki/Modules

**Comment by heimweh** [comment]
Thank you so much for opening this issue @chenrui333 :pray:
This is done so I'll close this for now but feel free to re-open if you want.
