### ISSUE TITLE
Feature: Make attribute start_day_of_week accept an array of days.

### ISSUE THREAD

**Issue by jaceq** [terraform-providers/terraform-provider-pagerduty#124]
terraform 0.11.3
pagerduty provider: 1.2.1

It would be really cool if restriction 'weekly_restriction' could accept array of days in start_day_of_week. My use case is that we have different support hours during the week and different at weekends. Currently I had to do 7 restrictions, one per day: 

    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "07:00:00"
      duration_seconds  = 54000
      start_day_of_week = 1
    }

    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "07:00:00"
      duration_seconds  = 54000
      start_day_of_week = 2
    }

    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "07:00:00"
      duration_seconds  = 54000
      start_day_of_week = 3
    }

    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "07:00:00"
      duration_seconds  = 54000
      start_day_of_week = 4
    }

    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "07:00:00"
      duration_seconds  = 54000
      start_day_of_week = 5
    }

    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "09:00:00"
      duration_seconds  = 43200
      start_day_of_week = 6
    }
    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "09:00:00"
      duration_seconds  = 43200
      start_day_of_week = 7
    }

What I think would be very cool: 

    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "07:00:00"
      duration_seconds  = 54000
      start_day_of_week = [1,2,3,4,5]
    }
    restriction {
      type              = "weekly_restriction"
      start_time_of_day = "09:00:00"
      duration_seconds  = 43200
      start_day_of_week = [6,7]
    }

This would simplify .tf file quite a bit.

Thanks!

**Comment by ianwsperber** [comment]
This is fairly straightforward to accomplish using a dynamic `for` block in Terraform 0.12

```
# Restrict 10AM - 4PM, Mo - Fr
dynamic "restriction" {
      for_each = [1, 2, 3, 4, 5]

      content {
        type              = "weekly_restriction"
        start_time_of_day = "10:00:00"
        duration_seconds  = "${6 * 60 * 60}"
        start_day_of_week = restriction.value
      }
    }
```

**Comment by heimweh** [comment]
Since this is fairly easy to accomplish now in Terraform 0.12 I'll go ahead and close this issue @jaceq, but feel free to re-open at any time.
