### ISSUE TITLE
Error [Url can't be empty] with resource "pagerduty_extension"

### ISSUE THREAD

**Issue by heldersepu** [terraform-providers/terraform-provider-pagerduty#131]
### Terraform Version
Terraform v0.11.13

### Affected Resource(s)
pagerduty_extension

### Terraform Configuration Files
```hcl
resource "pagerduty_extension" "slack"{
  name = "My Web App Extension"
   extension_schema = "${data.pagerduty_extension_schema.webhook.id}"
  extension_objects    = ["${pagerduty_service.example.id}"]

  config = <<EOF
{
    "restrict": "any",
    "notify_types": {
            "resolve": false,
            "acknowledge": false,
            "assignments": false
    },
    "access_token": "XXX"
}
EOF

}.
```

Here is the full code:
https://github.com/heldersepu/hs-scripts/blob/master/TerraForm/pagerduty/pagerduty.tf

### Debug Output
```
Error: Error applying plan:

1 error(s) occurred:

* ....pagerduty_extension.slack: 1 error(s) occurred:

* pagerduty_extension.slack: 
  POST API call to https://api.pagerduty.com/extensions failed 400 Bad Request. 
  Code: 2001, Errors: [Url can't be empty], Message: Invalid Input Provided
```

### Expected Behavior
It should complete without errors?

### Actual Behavior
We get that strange 'Url can't be empty' error but according to the documentation the endpoint_url is optional

**Comment by pdecat** [comment]
Hi, the [endpoint URL is optional API wise](https://api-reference.pagerduty.com/#!/Extensions/post_extensions) in most cases, and the provider was updated to match that behavior in #83, but I believe it can be required in some cases such as the `pagerduty_extension_schema` named `Generic V2 Webhook` [you are using here](https://github.com/heldersepu/hs-scripts/blob/master/TerraForm/pagerduty/pagerduty.tf#L19).

For the `pagerduty_extension_schema` named `Slack`, the API accepts `pagerduty_extension` with no `endpoint_url` defined.

**Comment by heldersepu** [comment]
@pdecat would be nice if that:
>  optional in most cases ... it can be required in some cases
was included in the documentation

I'm trying that  the pagerduty_extension_schema named Slack, let see if it works...

**Comment by karancode** [comment]
@heimweh @pdecat I updated the documentation #164. PTAL.
