### ISSUE TITLE
New service created with terraform did not show up in my team

### ISSUE THREAD

**Issue by chenrui333** [terraform-providers/terraform-provider-pagerduty#132]
It seems like the newly created `pagerduty_service` did not show up in my team.

I dont think I had issue ebfore for creating the `pagerduty_service` resources before. 

Also going to file a PD support ticket.

**Comment by heimweh** [comment]
Hi @chenrui333,

Did you find out what happened here? 

Thanks,

Alexander

**Comment by heimweh** [comment]
Hi @chenrui333,

closing this for now but feel free to re-open at any time.
