### ISSUE TITLE
Changes triggered when list order not as expected in maintenance_window

### ISSUE THREAD

**Issue by seemonicago** [terraform-providers/terraform-provider-pagerduty#137]
### Description
When creating a maintenance window that lists multiple services, pagerduty appears to store and list them in lexicographical order by name (not id), regardless of the order pager duty creates them in. If the list of services are not in the same order, it will continue to trigger a change event.

Example: 

Variables values:
```
email_service_name = Email
prometheus_service_name = Prometheus
uptime_service_name = Uptime.com
wavefront_service_name = Wavefront
```

Maintenance window with a list of services that is not in lexicographical order by name:
```
resource "pagerduty_maintenance_window" "maintenance" {
  description = "Scheduled maintenance for upgrades"
  start_time  = "2019-06-26T22:00:00-05:00"
  end_time    = "2019-06-27T04:00:00-05:00"
  services    = ["${pagerduty_service.email.id}", "${pagerduty_service.wavefront.id}", "${pagerduty_service.prometheus.id}", "${pagerduty_service.uptime.id}"]
}
```

### Terraform Version
Terraform v0.12.2
+ provider.pagerduty v1.3.0

### Affected Resource(s)
Please list the resources as a list, for example:
- pagerduty_maintenance_window

### Expected Behavior
There should be no changes to apply. The list of ID's should be parsed so that the order does not trigger a change.

### Actual Behavior
Changes to be applied are shown. These changes are reordering the existing ID's.
```
  # pagerduty_maintenance_window.maintenance will be updated in-place
  ~ resource "pagerduty_maintenance_window" "maintenance" {
        description = "Scheduled maintenance for upgrades"
        end_time    = "2019-06-27T02:00:00-07:00"
        id          = "{REDACTED}"
      ~ services    = [
          - "POL8DV8",
            "P8OKCFI",
          + "POL8DV8",
            "P4CZC3V",
            "PSXWE7Y",
        ]
        start_time  = "2019-06-26T20:00:00-07:00"
    }
```

### Steps to Reproduce
1. Create a maintenance window with multiple services as shown above. List the services in terraform in any order other than lexicographical by service name.

**Comment by heimweh** [comment]
Hi @seemonicago,

Thanks for reporting this.
I’ve opened #142 which should solve this issue.  

Best,

Alexander

**Comment by heimweh** [comment]
Hi @seemonicago,

a fix for this has been merged and will be available in the next release of the PagerDuty provider.

Once again, thank you so much for reporting this :pray:

Best,

Alexander

**Comment by seemonicago** [comment]
Thanks so much @heimweh!
