### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by luis-silva** [terraform-providers/terraform-provider-pagerduty#139]
Hi,

Can we have a more regular release schedule for this provider? The merged PRs take quite a long time to get released, the last release was a couple of months ago. I'd like to make a few more improvements to the provider, we're using it extensively, but we're finding it hard to get the benefit of new features/bug fixes if we can't release them faster.

Thanks!

**Comment by heimweh** [comment]
Hi @luis-silva ,

Thank you so much for bringing this up. 
Will definitely take this into consideration for future releases. 

I’ll go ahead and close this for now but feel free to reopen at anytime. 

Best,

Alexander
