### ISSUE TITLE
Feature: Add data source for service

### ISSUE THREAD

**Issue by TomTucka** [terraform-providers/terraform-provider-pagerduty#140]
Add a data source for a service... Currently creating a service integration per stack in aws but this requires the ID of the service in which the integrations belong to. 

We manage all our services and teams centrally then each project would like to create their integration but currently, you have to create the service alongside the integration which becomes tricky because an apply will fail as the resource already exists

**Comment by TomTucka** [comment]
opened a PR for this #141

**Comment by heimweh** [comment]
Thank you so much for implementing this @TomTucka! 👍
This will be released with the next version of the PagerDuty provider.
