### ISSUE TITLE
Ability to create rule sets, and assign an event rule to a rule set

### ISSUE THREAD

**Issue by arjunnayak** [terraform-providers/terraform-provider-pagerduty#176]
Hi,

We are seeing the ability in the PagerDuty UI to create rule sets, which we find is great for creating isolation between different sets of alerts and incidents. We would like to automate this rule set creation through terraform, and additionally be able to tie event rule resources to a particular rule set resource. Is this already on the roadmap? We're noticing that there isn't API documentation for rule sets yet, so I suspect this feature is blocked until the public API is opened up. 

This is a feature request so I skipped details for the other sections.

### Terraform Version
0.12.18

**Comment by stmcallister** [comment]
You are correct. The API for Rule Sets is currently not generally available. But, the plan is to add Rule Sets to the Provider once the API allows it.

**Comment by RabihHallage** [comment]
Hello, we would like to have this feature as well ... any estimation when this gonna be ready?

**Comment by stmcallister** [comment]
@RabihHallage I'm told that the API endpoint should be ready by the end of the quarter. And then once it's released, I can  build the resource in the provider.

**Comment by RabihHallage** [comment]
@stmcallister Thanks!!!

**Comment by joshk0** [comment]
Any updates here?

**Comment by stmcallister** [comment]
Merged Rulesets in today! Closing issue.

**Comment by stmcallister** [comment]
Merged Rulesets in today! Closing issue.
