### ISSUE TITLE
Enchancement request: support Conference Bridge Settings in pagerduty_service resource

### ISSUE THREAD

**Issue by pickgr** [terraform-providers/terraform-provider-pagerduty#182]
### Terraform Version
Terraform v0.12.21
+ provider.pagerduty v1.4.2

### Affected Resource(s)
- pagerduty_service

### Important Factoids
I'm not sure if the API supports this yet - maybe that's why it's not available.

I've verified that the field(s) can be set in the UI without causing drift for existing codified service resources.

### References
I didn't see any other open requests for this.

**Comment by stmcallister** [comment]
Hey @pickgr! Thanks for the request! I checked with the engineering team responsible for this part of the product and this is not in the API today. And, it's not on any short-term road maps. Going to close the issue. Please repost if you have any further questions.
