### ISSUE TITLE
pagerduty_extension/extension_objects requires list of one

### ISSUE THREAD

**Issue by skyzyx** [terraform-providers/terraform-provider-pagerduty#189]
### Terraform Version

```
Terraform v0.12.23
+ provider.pagerduty v1.5.0
+ provider.random v2.2.1
```

### Affected Resource(s)

- pagerduty_extension

### Terraform Configuration Files

```hcl
# https://www.terraform.io/docs/providers/pagerduty/r/extension.html
resource "pagerduty_extension" "slack_prod" {
  name             = "Outbound to Slack (Production)"
  extension_schema = data.pagerduty_extension_schema.slack.id

  # Attach to service.
  extension_objects = [
    pagerduty_service.prod.id,
    pagerduty_service.nonprod.id,
  ]
}
```

### Debug Output

https://gist.github.com/skyzyx/b55bb78a9c1bdf03baafd6feb0945b97

### Expected Behavior

Since `extension_objects` asks for a list, I expected that you can pass more than one service ID.

### Actual Behavior

You cannot pass more than one service ID. Perhaps this could be fixed for v2.0?

```
Error: POST API call to https://api.pagerduty.com/extensions failed 400 Bad Request. Code: 2001, Errors: [Only one extension object allowed], Message: Invalid Input Provided

  on ../extensions.tf line 8, in resource "pagerduty_extension" "slack":
   8: resource "pagerduty_extension" "slack" {
```

### Steps to Reproduce

1. `terraform apply`

**Comment by scottrobertson** [comment]
Same here

**Comment by stmcallister** [comment]
Yeah, this is a reflection of how the underlying PagerDuty API works. It's expecting a list of one. There have been discussions internally at PagerDuty, and at this time there are no immediate plans to change this.

**Comment by scottrobertson** [comment]
Oh really? What an odd API choice ha.

Anyway, thank you!

**Comment by stmcallister** [comment]
I agree with you. :) Going to close this. But please repost if you have any further questions.

**Comment by mrboso** [comment]
Would it be possible to fix the limitation of only one object in array? It would significantly reduce the complexity of my code. Thanks

**Comment by scottrobertson** [comment]
@mrboso The API does not support it, so they would need to change that first. I recommend reaching out to support for that.
