### ISSUE TITLE
Support Service Event Rules resource

### ISSUE THREAD

**Issue by julianvmodesto** [terraform-providers/terraform-provider-pagerduty#202]
Global Rulesets and Global Event Rules (legacy) are resources supported through the provider, but Service Event Rules are not yet supported.

[See the documentation on PagerDuty Rulesets.](https://support.pagerduty.com/docs/rulesets)

**Comment by h3x89** [comment]
I think that there is not yet possibility to manage that even via api:
https://developer.pagerduty.com/api-reference/reference/REST/openapiv3.json/paths/~1services~1%7Bid%7D/put
:(

**Comment by stmcallister** [comment]
@julianvmodesto Thanks for the request! Unfortunately, Service Level Event Rules are not supported by the PagerDuty API. Once it is, we'll add it to the `ruleset` and `ruleset_rule` resources.

**Comment by stmcallister** [comment]
Going to close this issue for now. but, when the service level event rules API is made available, we also work on getting this added to the provider.

**Comment by Geethree** [comment]
@stmcallister Any timelines on when the Service Level Event Rules may be supported via the PagerDuty API? This would be quite handy.

**Comment by pivno** [comment]
@stmcallister  @Geethree early-access support is now available https://developer.pagerduty.com/api-reference/docs/CHANGELOG.md#2020-09-16

**Comment by tdmalone** [comment]
Since this hasn't been re-opened yet, I've recreated it at #279!
