### ISSUE TITLE
About schedule override

### ISSUE THREAD

**Issue by chenrui333** [terraform-providers/terraform-provider-pagerduty#203]
I wonder if there is anyway that I can do schedule override, my understanding is it is not supported via the API yet?

**Comment by stmcallister** [comment]
There is an API for schedule overrides, but it currently hasn't made its way to the Terraform provider yet.

**Comment by chenrui333** [comment]
Sorry for creating the duplicating issues in both two repos.

Closing as we have discussed in https://github.com/heimweh/go-pagerduty/issues/36.
