### ISSUE TITLE
terraform 0.12.x compatibility

### ISSUE THREAD

**Issue by chenrui333** [terraform-providers/terraform-provider-pagerduty#222]
I am using this provider with 0.12, and thinking to update the docs to reflect tf 0.12 syntax changes.

While I was doing that, I noticed this provider declaration in here.
https://github.com/terraform-providers/terraform-provider-pagerduty/blob/8b4e53339d5ed55f6902cae8807527be012ddc9c/pagerduty/provider.go#L63-L71

Is there any terraform 0.12 compatibility concern in here?

Thanks!

**Comment by stmcallister** [comment]
Thanks for bringing this up and for the PR! I've reviewed and merged it. So, I'm going to close this issue.
