### ISSUE TITLE
Service dependency creation works but Terraform reports failure

### ISSUE THREAD

**Issue by matt-canty-dragon** [terraform-providers/terraform-provider-pagerduty#226]
### Terraform Version
```
Terraform v0.12.24
+ provider.pagerduty v1.7.1
```

### Affected Resource(s)
- pagerduty_service_dependency

### Terraform Configuration Files
```hcl
resource pagerduty_service_dependency service_dependency {
  dependency {
    dependent_service {
      id   = "PXXXXXA"
      type = "service"
    }
    supporting_service {
      id   = "PXXXXXB"
      type = "service"
    }
  }
}
```

### Debug Output
```
pagerduty_service_dependency.service_dependency: Creating...
pagerduty_service_dependency.service_dependency: Still creating... [10s elapsed]
pagerduty_service_dependency.service_dependency: Still creating... [20s elapsed]
pagerduty_service_dependency.service_dependency: Still creating... [30s elapsed]

Error: GET API call to https://api.pagerduty.com/service_dependencies/business_services/PXXXXXA failed 404 Not Found. Code: 404, Errors: [], Message: Service Not Found

  on main.tf line 14, in resource "pagerduty_service_dependency" "service_dependency":
  14: resource pagerduty_service_dependency service_dependency {
```

### Expected Behavior
Terraform apply should pass

### Actual Behavior
The dependency is actually created in PagerDuty but the apply fails regardless.

![image](https://user-images.githubusercontent.com/56073682/81705902-72653880-9467-11ea-8ab4-cc9b9ca6aad4.png)

It looks like in the URL it is trying to get _business service_ dependency, but this is a _technical service_. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by stmcallister** [comment]
Ah, right. As it stands, the Provider assumes that `service_dependencies` are `business_service` objects supported by `service` objects. The functionality for `service` to `service` is still in Beta in the PagerDuty web UI.  So, the plan was to make the feature available in the provider when it came out of Beta. I'll check with the Services team to see if there's a timetable there.

**Comment by matt-canty-dragon** [comment]
Ok sure thing. Thanks.

**Comment by stmcallister** [comment]
Going to close this, as creating the feature is on our radar. Please open a new issue if you have any further issues.
