### ISSUE TITLE
Permadiff on schedule start time

### ISSUE THREAD

**Issue by 2rs2ts** [terraform-providers/terraform-provider-pagerduty#34]
### Terraform Version
0.10.2

(This was not an issue on 0.9.10. It became an issue after upgrading.)

### Affected Resource(s)
- pagerduty_schedule

### Terraform Configuration Files
```hcl
resource "pagerduty_schedule" "our_primary_on_call" {
  name      = "Our Primary On-call"
  time_zone = "America/Chicago"

  layer {
    start                        = "2017-08-08T17:16:03-05:00" # Rotation flips at 11AM Mon, Chi time
    rotation_virtual_start       = "2017-07-31T11:00:00-05:00"
    rotation_turn_length_seconds = 604800                      # 1 week

    users = ["${data.pagerduty_user.on_call_users.*.id}"]
  }
}
```

### Debug Output
I can provide an isolated example and produce debug output if necessary but would rather not have to do so and then also redact our private credentials.

### Expected Behavior
No diff should be produced after applying this once

### Actual Behavior
Subsequent plans, applies show a diff:

```
  ~ module.pagerduty.pagerduty_schedule.our_primary_on_call
      layer.0.start: "2017-08-23T15:09:35-05:00" => "2017-08-08T17:16:03-05:00"
```

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan`

**Comment by heimweh** [comment]
Hi @2rs2ts, thanks for reporting this issue.

I managed to reproduce this issue, and I've published a fix here: #35. 

I'm very sorry about this and I hope this fix should resolve the issue you're currently experiencing.

Best,
Alexander

**Comment by pepov** [comment]
Hi, this is great! When can we expect the next release?

**Comment by 2rs2ts** [comment]
Closing because the fix was merged.

**Comment by 2rs2ts** [comment]
But yes please release the fix. It's been almost 2 months since the fix was merged.

**Comment by joseluis-fw** [comment]
@2rs2ts Any plan to include this in a new release?

**Comment by 2rs2ts** [comment]
@joseluis-fw I'm not a maintainer, so the idea has not crossed my mind :)

**Comment by joseluis-fw** [comment]
@heimweh Any plan to include cut a new release?
