### ISSUE TITLE
Incident Timeouts in Services

### ISSUE THREAD

**Issue by h3x89** [terraform-providers/terraform-provider-pagerduty#41]
Hi,

There is no possibility to disabled Acknowledgement timeout and Auto-resolution in Services:
![image](https://user-images.githubusercontent.com/3736964/31602563-d0a79846-b25d-11e7-984c-1f6066765f7f.png)

Do you plan to work on this feature?

**Comment by pdecat** [comment]
I need that too, so I'll give it a shot.

**Comment by pdecat** [comment]
Probably caused by `omitempty` option set in the JSON format strings of those fieds: 
https://github.com/heimweh/go-pagerduty/blob/master/pagerduty/service.go#L63
https://github.com/heimweh/go-pagerduty/blob/master/pagerduty/service.go#L66
