### ISSUE TITLE
Extend service integration

### ISSUE THREAD

**Issue by h3x89** [terraform-providers/terraform-provider-pagerduty#42]
Hi there,

Right not there is possibility to set:
```
The service type. Can be: aws_cloudwatch_inbound_integration, cloudkick_inbound_integration, event_transformer_api_inbound_integration, generic_email_inbound_integration, generic_events_api_inbound_integration, keynote_inbound_integration, nagios_inbound_integration, pingdom_inbound_integrationor sql_monitor_inbound_integration.
```

Could you extend it and add NewRelic, Bosun and StackDriver?

**Comment by pdecat** [comment]
The list of supported services is managed in the go-pagerduty client library: https://github.com/mathyourlife-fitbit/terraform-provider-pagerduty/blob/master/pagerduty/resource_pagerduty_service_integration.go#L35

**Comment by pdecat** [comment]
A NewRelic service integration is just a `generic_events_api_inbound_integration` bound a specific vendor: https://support.pagerduty.com/v1/docs/services-and-integrations#section-create-a-vendor-specific-service-via-api

The vendors IDs can be retrieved from the API reference: https://v2.developer.pagerduty.com/page/api-reference#!/Vendors/get_vendors

As of today, here is the stock vendor list:

```
# curl -s -X GET --header 'Accept: application/vnd.pagerduty+json;version=2' --header 'Authorization: Token token=**************' 'https://api.pagerduty.com/vendors' | jq '.vendors[].name' | sort
"AdmanTIC"
"Airbrake"
"AlertBot"
"AlertFox"
"AlertSite UXM"
"Amazon Cloudwatch"
"Apex Ping"
"Apica"
"AppDynamics"
"AppFirst"
"AppFormix"
"Custom Event Transformer"
"Datadog"
"HipChat to PagerDuty"
"JIRA Software"
"Microsoft Azure"
"Nagios"
"New Relic"
"Pingdom BeepManager"
"Sensu"
"ServiceNow (Legacy)"
"Slack to PagerDuty"
"Splunk"
"Zabbix"
"Zendesk"
```

The `pagerduty_vendor` datasource can be used to retrieve the corresponding IDs.

I believe other vendors will need to be added by oneself.

**Comment by heimweh** [comment]
Hi @h3x89, I'm gonna go ahead and close this but feel free to re-open if you want.

Best regards,

Alexander
