### ISSUE TITLE
[Enhancement] Service Extensions

### ISSUE THREAD

**Issue by DWSR** [terraform-providers/terraform-provider-pagerduty#46]
It would be awesome to be able to add service extensions via Terraform (for example, reporting to Slack).

API Reference is here: https://v2.developer.pagerduty.com/v2/page/api-reference#!/Extensions/get_extensions

**Comment by pdecat** [comment]
I believe it is the same as #11

**Comment by DWSR** [comment]
It is, but I feel that the issue should not have been closed due to a lack of support in the Go client. There is a potential solution that does not require enhancing the PD Go SDK. Even if that were not the case, it feels very inappropriate to close it because the upstream doesn't support it when it's an obvious deficiency. Leaving the issue open brings visibility and the chance that a Golang dev will come along and enhance the SDK. Agree that there should be an issue filed on it and I have already done so.

**Comment by pdecat** [comment]
I think #42 will get reopened eventually, given go-pagerduty is *primarily used by the PagerDuty provider in Terraform* as stated in its README.

I've planned to work on implementing service extensions in the near future if no one else steps in before me.

**Comment by DWSR** [comment]
If I'm understanding this correctly, #42 refers to integrations, not extensions. It would make sense to have a separate issue for extensions, no?

**Comment by pdecat** [comment]
Oops, meant #11.

**Comment by tigris** [comment]
Whilst I approve of this upgrade, according to https://v2.developer.pagerduty.com/v2/page/api-reference#!/Extension_Schemas/get_extension_schemas the specific request for slack may not be possible?

> Some Extension Schemas that require OAuth Authorization to be setup, such as the Slack and HipChat extension, cannot be configured through the API.

**Comment by pdecat** [comment]
The OAuth auhorization will indeed have to be done by hand out of band.

**Comment by automaticgiant** [comment]
the work could be started without oauth support if documented, and continued later. my use case, for example, doesn't require it, so that would work for me.
it may also (since there's the outofbandness) point to a generic tf oauth data source or something that could be used without bloating the service extension feature (which i guess would be a new resource).

**Comment by mbelekar** [comment]
I have added #69 to enable extensions.

**Comment by catsby** [comment]
Hello! I merged #69, so I'm going to close this. Let me know if you have any questions

**Comment by catsby** [comment]
I just released v1.0.0 of the PagerDuty Provider with these new features! Please see the [CHANGELOG](https://github.com/terraform-providers/terraform-provider-pagerduty/blob/master/CHANGELOG.md#100-march-08-2018)
