### ISSUE TITLE
Validate days of week

### ISSUE THREAD

**Issue by kushmansingh** [terraform-providers/terraform-provider-pagerduty#48]
I mistakenly assumed the days of the week were 0 indexed. Some validation around this would be nice.

### Terraform Version
All versions

### Affected Resource(s)
Please list the resources as a list, for example:
- pagerduty_service

### Terraform Configuration Files
```hcl
resource "pagerduty_service" "foo" {
	name                    = "foo"
	description             = "bar bar bar"
	auto_resolve_timeout    = 3600
	acknowledgement_timeout = 3600
	escalation_policy       = "${pagerduty_escalation_policy.foo.id}"
	}
	support_hours = [{
		type         = "fixed_time_per_day"
		time_zone    = "America/Lima"
		start_time   = "09:00:00"
		end_time     = "17:00:00"
		days_of_week = [0, 1, 2, 3, 4, 5 ]
	}]
}
```

### Expected Behavior
What should have happened?
terraform plan should have failed with a validation error

### Actual Behavior
What actually happened?
It succeeded but made the state wonky and showed changes for the field on all subsequent plans.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by aerostitch** [comment]
Currently the ValidateFunc is not yet supported on lists or sets.
If it was you'd be able to just use the following patch after doing a `govendor fetch github.com/hashicorp/terraform/helper/validation@=v0.10.0`:
``` git diff pagerduty/resource_pagerduty_service.go
diff --git a/pagerduty/resource_pagerduty_service.go b/pagerduty/resource_pagerduty_service.go
index fda08c3..12a1456 100644
--- a/pagerduty/resource_pagerduty_service.go
+++ b/pagerduty/resource_pagerduty_service.go
@@ -5,6 +5,7 @@ import (
        "strconv"
 
        "github.com/hashicorp/terraform/helper/schema"
+       "github.com/hashicorp/terraform/helper/validation"
        "github.com/heimweh/go-pagerduty/pagerduty"
 )
 
@@ -140,10 +141,11 @@ func resourcePagerDutyService() *schema.Resource {
                                                        Optional: true,
                                                },
                                                "days_of_week": {
-                                                       Type:     schema.TypeList,
-                                                       Optional: true,
-                                                       MaxItems: 7,
-                                                       Elem:     &schema.Schema{Type: schema.TypeInt},
+                                                       Type:         schema.TypeList,
+                                                       Optional:     true,
+                                                       MaxItems:     7,
+                                                       Elem:         &schema.Schema{Type: schema.TypeInt},
+                                                       ValidateFunc: validation.IntBetween(1, 7),
                                                },
                                        },
                                },
```
but until it's supported that's not feasible in a clean way AFAIK.

**Comment by aerostitch** [comment]
@kushmansingh I added the info about the days_of_week field in the doc in #56.
Let me know if that's sufficient for you. Given the previous explanations, it seems that it won't be possible to programatically validate that anytime soon anyway, so adding some doc about it may be enough.

**Comment by heimweh** [comment]
I'm gonna go ahead and close this since we merged the documentation PR, 
but feel free to re-open this if you feel like this hasn't been resolved.
