### ISSUE TITLE
Changing a PagerDuty service's support hours or scheduled actions recreates the service

### ISSUE THREAD

**Issue by lukeck** [terraform-providers/terraform-provider-pagerduty#53]
Changing a PagerDuty service's support hours or scheduled actions recreates the service.

This appears to be intentional as the [docs](https://www.terraform.io/docs/providers/pagerduty/r/service.html) state
> Changes to support_hours necessitate re-creating the service resource.

and

> Changes [to scheduled actions] necessitate re-createing the service resource.

Re-creating a service under these circumstances causes us problems:
- we need to update our systems to post alerts to a new endpoint
- we lose alert history

It appears that this behaviour is controlled through hard-coded `true` values for [support hours](https://github.com/terraform-providers/terraform-provider-pagerduty/blob/master/pagerduty/resource_pagerduty_service.go#L120) and [scheduled actions](https://github.com/terraform-providers/terraform-provider-pagerduty/blob/master/pagerduty/resource_pagerduty_service.go#L151). If I was to change these to `false`, what, if anything would break? My initial testing indicates it seems okay when adding support hours or scheduled actions entities to a service, updating them, or removing them from a service.

This is currently a blocker for us so I'm more than happy to put together a pull request if you can point me in the right direction.

**Comment by tigris** [comment]
@lukeck and I have a PR and spec for this ready to go if there is agreement it's a wanted change.

**Comment by heimweh** [comment]
Hi @lukeck, @tigris thanks for reporting this issue. 

Your observation is correct, updating `support_hours` and `scheduled_actions` seems to work correctly without having to re-create the resource. If you have a PR ready, I'd love to review it and get this fix in :)

Best,

Alexander

**Comment by mbelekar** [comment]
@heimweh I created PR #60 . Since we haven't added acceptance tests (currently we do not have a dedicated test environment), can you give some inputs on how we can write tests for this.
