### ISSUE TITLE
Please release a 0.2 

### ISSUE THREAD

**Issue by jamielennox** [terraform-providers/terraform-provider-pagerduty#57]
Hey, 

Pagerduty is pushing people to be using their v2 events API and to configure that with terraform we need to have a released version of #40.

Can you please make a new release please.

Thanks

**Comment by tombuildsstuff** [comment]
Hi @jamielennox 

Thanks for opening this issue

Just to let you know that I've just kicked off the release process for v0.1.4 of the PagerDuty Provider which should be available shortly

Thanks!

**Comment by tombuildsstuff** [comment]
hey @jamielennox 

v0.1.3 of the PagerDuty now available - as such I'm going to close this issue

Thanks!
