### ISSUE TITLE
Unable to locate extension schema

### ISSUE THREAD

**Issue by EthanBlackburn** [terraform-providers/terraform-provider-pagerduty#77]
### Terraform Version
Terraform v0.10.7
Pagerduty Provider v1.0.0

### Affected Resource(s)
- pagerduty_extension_schema

### Terraform Configuration Files
```hcl
data "pagerduty_extension_schema" "slack" {
  name = "Slack"
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
Terraform should have created a `pagerduty_extension` resource using the schema

### Actual Behavior
Terraform output an error
```
Error refreshing state: 1 error(s) occurred:

* data.pagerduty_extension_schema.slack: 1 error(s) occurred:

* data.pagerduty_extension_schema.slack: data.pagerduty_extension_schema.slack: Unable to locate any extension schema with the name: Slack
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create pagerduty_extension_schema object like
```
data "pagerduty_extension_schema" "slack" {
  name = "Slack"
}
```
2. Create a `pagerduty_extension` resource which references the `pagerduty_extension_schema`
3. `terraform plan`

### Important Factoids
This was working a few days ago. Haven't made any changes to our codebase

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by pdecat** [comment]
Looks like this happens when there are too many results to fit in a single page and the looked up extension schema isn't in the first page.
