### ISSUE TITLE
Add support for push_notification_contact_method type in pagerduty_user_contact_method resource

### ISSUE THREAD

**Issue by pa-yourserveradmin-com** [terraform-providers/terraform-provider-pagerduty#86]
### Versions

Terraform: v0.11.7
Pagerduty: v1.1.0

### Affected Resource(s)

- pagerduty_user_contact_method

### Terraform Configuration Files

```hcl
provider "pagerduty" {}

resource "pagerduty_user" "example" {
  color       = "green"
  description = ""
  email       = "example@example.com"
  job_title   = "Example"
  name        = "example"
  role        = "user"
}

resource "pagerduty_user_contact_method" "example" {
  address = "<LONG_NOTIFICATION_ID>"
  label   = "Label"
  type    = "push_notification_contact_method"
  user_id = "${pagerduty_user.example.id}"
}
```

### Expected Behavior

`terraform plan` and `terraform apply` complete successfully.

### Actual Behavior

`terraform plan` and `terraform apply` fail with errors like this:
```
Error: pagerduty_user_contact_method.example: "push_notification_contact_method" is an invalid value for argument type. Must be one of []string{"email_contact_method", "phone_contact_method", "sms_contact_method"}
```

### Steps to Reproduce

1. Copy example configuration provided above;
2. Run `terraform plan` or `terraform apply` and see error mentioned in [Actual Behavior](#actual-behavior) section.

**Comment by pa-yourserveradmin-com** [comment]
Here is link to [patch](https://gist.github.com/pa-yourserveradmin-com/d25a326e5e3710934c892f7030260728#file-push_notification_contact_method-patch) with functional changes (without documentation and tests) which solves this issue.

**Comment by zekefast** [comment]
Guys, is anything could be done in order to merge patch for the issue?

**Comment by tdmalone** [comment]
@zekefast If you need to use this in the meantime, you can build a custom provider locally - just pull down the repo and merge locally, follow the instructions [here](https://github.com/terraform-providers/terraform-provider-pagerduty#building-the-provider), and symlink the provider into your folder's .terraform directory.

**Comment by zekefast** [comment]
@tdmalone, Problem is that we need to use it with Terraform Enterprise. Do you know is it possible to use self-created providers with IT?

**Comment by zekefast** [comment]
May be @pa-yourserveradmin-com or I could improve patch somehow in order to be able to merge it? We just need a bit or guidance about what should be done.
